spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 6.0.2.52:8848
    gateway:
      routes:
        - id: Server
          uri: lb://server
          predicates:
            - Path=/api/server/**
          filters:
              - RewritePath=/api/server/(?<segment>.*),/$\{segment}
server:
  port: 8080